// src/redux/pokemon/pokemonTypes.js

export const FETCH_POKEMONS_START = 'pokemon/FETCH_POKEMONS_START';
export const FETCH_POKEMONS_SUCCESS = 'pokemon/FETCH_POKEMONS_SUCCESS';
export const FETCH_POKEMONS_FAILURE = 'pokemon/FETCH_POKEMONS_FAILURE';

export const LOAD_MORE_POKEMONS_START = 'pokemon/LOAD_MORE_POKEMONS_START';
export const LOAD_MORE_POKEMONS_SUCCESS = 'pokemon/LOAD_MORE_POKEMONS_SUCCESS';
export const LOAD_MORE_POKEMONS_FAILURE = 'pokemon/LOAD_MORE_POKEMONS_FAILURE';

export const FETCH_POKEMON_DETAILS_START = 'pokemon/FETCH_POKEMON_DETAILS_START';
export const FETCH_POKEMON_DETAILS_SUCCESS = 'pokemon/FETCH_POKEMON_DETAILS_SUCCESS';
export const FETCH_POKEMON_DETAILS_FAILURE = 'pokemon/FETCH_POKEMON_DETAILS_FAILURE';

export const FILTER_POKEMONS_BY_TYPE = 'pokemon/FILTER_POKEMONS_BY_TYPE';
export const CLEAR_POKEMON_DETAILS = 'pokemon/CLEAR_POKEMON_DETAILS';
export const SET_SEARCH_QUERY = 'pokemon/SET_SEARCH_QUERY';